# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

#cmake_minimum_required(VERSION 3.20)
#project(connext_sender_receiver CXX)

find_package(holoscan 3.0 REQUIRED CONFIG PATHS "/opt/nvidia/holoscan")

add_executable(connext_sender_receiver
  main.cpp
  connext_common.cpp
)

target_compile_features(connext_sender_receiver PRIVATE cxx_std_17)

target_link_libraries(connext_sender_receiver
  PRIVATE
    holoscan::core
    holoscan::ops::connext_ops
    holoscan::ops::connext_lib
)

add_custom_target(connext_sender_receiver_yaml
  COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_CURRENT_SOURCE_DIR}/connext_sender.yaml" ${CMAKE_CURRENT_BINARY_DIR}
  COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_CURRENT_SOURCE_DIR}/connext_receiver.yaml" ${CMAKE_CURRENT_BINARY_DIR}
  DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/connext_sender.yaml"
    "${CMAKE_CURRENT_SOURCE_DIR}/connext_receiver.yaml"
  BYPRODUCTS
    "${CMAKE_CURRENT_BINARY_DIR}/connext_sender.yaml"
    "${CMAKE_CURRENT_BINARY_DIR}/connext_receiver.yaml"
)

add_dependencies(connext_sender_receiver connext_sender_receiver_yaml)
